# Canonical configuration for the deployed dev environment.
#
# Committed on purpose, and NOT named terraform.tfvars, for two reasons:
#   1. CI must apply exactly what a human would. If this lived only in a
#      gitignored terraform.tfvars, a CI apply would silently fall back to
#      variable defaults - and enable_notifications defaults to false, so the
#      first automated deploy would DESTROY the entire notification stack.
#   2. terraform.tfvars is auto-loaded by `terraform test` too, which leaks
#      these values into module-level test runs. A file under environments/
#      is only read when passed explicitly with -var-file.
#
# Nothing secret belongs here - it is world-readable in the repo. The session
# secret is generated by random_password and stored in SSM; AWS credentials
# come from the two access-key secrets deploy.yml reads (this org's OIDC
# policy blocks AssumeRoleWithWebIdentity, so the dormant OIDC role
# infrastructure/bootstrap can create goes unused).
#
# Usage (both CI and local):
#   terraform apply -var-file=environments/dev.tfvars

aws_region  = "us-east-1"
environment = "dev" # NOT "prod": that enables ALB deletion protection and
# forbids notification_override_recipient below

bucket_force_destroy = true # lets `terraform destroy` succeed once the
# pinger and e2e suite have written objects

# Per-owner down/recovery emails. Now on the "domain" identity (Route 53 is
# live, so module.dns publishes the 3 DKIM CNAMEs automatically - see
# ses_dkim_tokens/enable_ses_dkim wiring in the root module). SES account is
# still in the sandbox (ProductionAccessEnabled: false as of this writing -
# confirm with `aws sesv2 get-account`), so every notification still
# redirects to one verified mailbox via notification_override_recipient.
#
# notification_verified_recipients MUST list that override address: it used
# to be verified "for free" as the sender identity itself back in "email"
# mode, but the domain switch replaces that identity, so the address needs
# its own explicit verified-recipient identity or sandbox sends to it bounce.
# AWS emails a verification link to the address itself after apply - click
# it before expecting any notification to actually arrive.
#
# Clear the override (and this list) once SES production access is granted -
# that's a separate AWS support request, not something Terraform can do.
enable_notifications              = true
notification_sender_identity_type = "domain"
notification_sender_domain        = "pulsemonitor.online"
notification_sender_email         = "alerts@pulsemonitor.online"
notification_override_recipient   = "aswathappa.d@northeastern.edu"
notification_verified_recipients  = ["aswathappa.d@northeastern.edu"]

# Route 53 / ACM / WAF (module.dns). pulsemonitor.online is registered at an
# external registrar (Namecheap); nameserver delegation to the Route 53 zone
# is live, so all three are on. Set explicitly rather than relying on the
# variables' own defaults - this file's whole point is to apply exactly what
# a human would, explicitly.
#
# Keep this comment in sync with the values below. enable_https is the one
# with teeth: every apply blocks on aws_acm_certificate_validation (10m
# resource timeout) while holding the non-cancelling deploy-dev concurrency
# group, so turning it on before delegation is live stalls each merge to
# main for 10 minutes before failing. enable_dns is non-blocking by
# comparison (creates the zone + a pending certificate). See
# modules/dns/main.tf's file header and infrastructure/README.md's "HTTPS
# rollout" section before changing either.
enable_dns   = true
enable_https = true
enable_waf   = true
