# Canonical configuration for the deployed dev environment.
#
# Committed on purpose, and NOT named terraform.tfvars, for two reasons:
#   1. CI must apply exactly what a human would. If this lived only in a
#      gitignored terraform.tfvars, a CI apply would silently fall back to
#      variable defaults - and enable_notifications defaults to false, so the
#      first automated deploy would DESTROY the entire notification stack.
#   2. terraform.tfvars is auto-loaded by `terraform test` too, which leaks
#      these values into module-level test runs. A file under environments/
#      is only read when passed explicitly with -var-file.
#
# Nothing secret belongs here - it is world-readable in the repo. The session
# secret is generated by random_password and stored in SSM; AWS credentials
# come from the GitHub OIDC role.
#
# Usage (both CI and local):
#   terraform apply -var-file=environments/dev.tfvars

aws_region  = "us-east-1"
environment = "dev" # NOT "prod": that enables ALB deletion protection and
# forbids notification_override_recipient below

bucket_force_destroy = true # lets `terraform destroy` succeed once the
# pinger and e2e suite have written objects

# Per-owner down/recovery emails. Verified as a single SES email identity
# (zero DNS work) with every notification redirected to that same mailbox,
# which is what makes this demonstrable while SES is still in the sandbox.
# Swap identity_type to "domain" and clear the override once Route 53 lands
# and SES production access is granted.
enable_notifications              = true
notification_sender_identity_type = "email"
notification_sender_email         = "aswathappa.d@northeastern.edu"
notification_sender_domain        = ""
notification_override_recipient   = "aswathappa.d@northeastern.edu"
notification_verified_recipients  = [] # must stay empty in "email" mode -
# the sender identity already verifies that mailbox as a recipient
